### ISSUE TITLE
Request for pre-processed data

### ISSUE THREAD

**Issue by AliMedVisionTech** [zhiwei-liang/MAXFormer#2]
Would you please send me your datasets on my email: bscs.f13.17@gmail.

**Comment by zhiwei-liang** [comment]
The dataset I used can be downloaded from the readme download link.

**Comment by AliMedVisionTech** [comment]
Thanks for the reply, and I got both datasets from the readme links. I have a question about ACDC training, how to train the ACDC dataset because the information is available only for the Synapse dataset.
