### ISSUE TITLE
Can you release the code to visualize the segmentation result of Synapse Multi-Organ Segmentation?

### ISSUE THREAD

**Issue by AliMedVisionTech** [zhiwei-liang/MAXFormer#3]

**Comment by zhiwei-liang** [comment]
Hello, you can write a Python script to filter slices that meet the criteria, just to determine whether the GT of a slice contains all the category labels. The visualization of Fig is achieved by importing the original image and segmentation mask into ITK-Snap.

**Comment by AliMedVisionTech** [comment]
Thank you so much for the response.
