### ISSUE TITLE
Would you please explain how you calculated the scores for each organ?

### ISSUE THREAD

**Issue by AliMedVisionTech** [zhiwei-liang/MAXFormer#4]
![11](https://github.com/zhiwei-liang/MAXFormer/assets/37287234/d4f1b1aa-d478-476a-b1f2-fd961f515973)

Hi, Thanks for your great work, and can you give me some help regarding each multi-organ result of Aorta,Kidnely etc.? How did you estimate because I got the average results for DSC and HD95 but still struggling to understand how to get the result for each organ, which you mentioned in your Table 3.

**Comment by zhiwei-liang** [comment]
save your model at the training stage and run test.py to get each multi-organ result.

**Comment by AliMedVisionTech** [comment]
I got it and thanks for the reply.
